import { ElementData } from "../types/periodic_type";

export const elements: ElementData[] = [
  // Chu kỳ 1
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    atomic_mass: 1.008,
    category: "diatomic nonmetal",
    xpos: 1,
    ypos: 1,
    melt: 13.99,
    boil: 20.271,
    summary: "Hydrogen is the lightest element.",
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    atomic_mass: 4.0026,
    category: "noble gas",
    xpos: 18,
    ypos: 1,
    melt: 0.95,
    boil: 4.222,
    summary: "Helium is a colorless, odorless noble gas.",
  },

  // Chu kỳ 2
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    atomic_mass: 6.94,
    category: "alkali metal",
    xpos: 1,
    ypos: 2,
    melt: 453.65,
    boil: 1603,
    summary: "Soft, silvery-white alkali metal.",
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    atomic_mass: 9.0122,
    category: "alkaline earth metal",
    xpos: 2,
    ypos: 2,
    melt: 1560,
    boil: 2742,
    summary:
      "A steel-gray, strong, lightweight and brittle alkaline earth metal.",
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    atomic_mass: 10.81,
    category: "metalloid",
    xpos: 13,
    ypos: 2,
    melt: 2349,
    boil: 4200,
    summary: "Produced entirely by cosmic ray spallation and supernovae.",
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    atomic_mass: 12.011,
    category: "polyatomic nonmetal",
    xpos: 14,
    ypos: 2,
    melt: 3800,
    boil: 4300,
    summary:
      "Nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    atomic_mass: 14.007,
    category: "diatomic nonmetal",
    xpos: 15,
    ypos: 2,
    melt: 63.15,
    boil: 77.36,
    summary: "A common element in the universe.",
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    atomic_mass: 15.999,
    category: "diatomic nonmetal",
    xpos: 16,
    ypos: 2,
    melt: 54.36,
    boil: 90.2,
    summary: "Highly reactive nonmetal, and an oxidizing agent.",
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    atomic_mass: 18.998,
    category: "diatomic nonmetal",
    xpos: 17,
    ypos: 2,
    melt: 53.53,
    boil: 85.03,
    summary: "The lightest halogen.",
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    atomic_mass: 20.18,
    category: "noble gas",
    xpos: 18,
    ypos: 2,
    melt: 24.56,
    boil: 27.07,
    summary: "A distinct reddish-orange glow.",
  },

  // Chu kỳ 3
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    atomic_mass: 22.99,
    category: "alkali metal",
    xpos: 1,
    ypos: 3,
    melt: 370.87,
    boil: 1156,
    summary: "Soft, silvery-white, highly reactive metal.",
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomic_mass: 24.305,
    category: "alkaline earth metal",
    xpos: 2,
    ypos: 3,
    melt: 923,
    boil: 1363,
    summary: "Shiny gray solid.",
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    atomic_mass: 26.982,
    category: "post-transition metal",
    xpos: 13,
    ypos: 3,
    melt: 933.47,
    boil: 2792,
    summary: "Silvery-white, soft, non-magnetic and ductile metal.",
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    atomic_mass: 28.085,
    category: "metalloid",
    xpos: 14,
    ypos: 3,
    melt: 1687,
    boil: 3538,
    summary:
      "Hard, brittle crystalline solid with a blue-grey metallic lustre.",
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    atomic_mass: 30.974,
    category: "polyatomic nonmetal",
    xpos: 15,
    ypos: 3,
    melt: 317.3,
    boil: 550,
    summary: "Exists in two major forms, white phosphorus and red phosphorus.",
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    atomic_mass: 32.06,
    category: "polyatomic nonmetal",
    xpos: 16,
    ypos: 3,
    melt: 388.36,
    boil: 717.8,
    summary: "Abundant, multivalent and nonmetallic.",
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomic_mass: 35.45,
    category: "diatomic nonmetal",
    xpos: 17,
    ypos: 3,
    melt: 171.6,
    boil: 239.11,
    summary: "Yellow-green gas.",
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    atomic_mass: 39.948,
    category: "noble gas",
    xpos: 18,
    ypos: 3,
    melt: 83.8,
    boil: 87.3,
    summary: "The third most abundant gas in the Earth's atmosphere.",
  },

  // Chu kỳ 4
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    atomic_mass: 39.098,
    category: "alkali metal",
    xpos: 1,
    ypos: 4,
    melt: 336.53,
    boil: 1032,
    summary:
      "Silvery-white metal that is soft enough to be cut with a knife with little force.",
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    atomic_mass: 40.078,
    category: "alkaline earth metal",
    xpos: 2,
    ypos: 4,
    melt: 1115,
    boil: 1757,
    summary: "Essential for living organisms.",
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    atomic_mass: 44.956,
    category: "transition metal",
    xpos: 3,
    ypos: 4,
    melt: 1814,
    boil: 3109,
    summary: "Silvery-white metallic d-block element.",
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    atomic_mass: 47.867,
    category: "transition metal",
    xpos: 4,
    ypos: 4,
    melt: 1941,
    boil: 3560,
    summary:
      "Lustrous transition metal with a silver color, low density, and high strength.",
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    atomic_mass: 50.942,
    category: "transition metal",
    xpos: 5,
    ypos: 4,
    melt: 2183,
    boil: 3680,
    summary: "Hard, silvery-grey, ductile, and malleable transition metal.",
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    atomic_mass: 51.996,
    category: "transition metal",
    xpos: 6,
    ypos: 4,
    melt: 2180,
    boil: 2944,
    summary: "Steely-grey, lustrous, hard and brittle transition metal.",
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    atomic_mass: 54.938,
    category: "transition metal",
    xpos: 7,
    ypos: 4,
    melt: 1519,
    boil: 2334,
    summary: "Not found as a free element in nature.",
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    atomic_mass: 55.845,
    category: "transition metal",
    xpos: 8,
    ypos: 4,
    melt: 1811,
    boil: 3134,
    summary: "By mass the most common element on Earth.",
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    atomic_mass: 58.933,
    category: "transition metal",
    xpos: 9,
    ypos: 4,
    melt: 1768,
    boil: 3200,
    summary: "Hard, lustrous, silver-gray metal.",
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    atomic_mass: 58.693,
    category: "transition metal",
    xpos: 10,
    ypos: 4,
    melt: 1728,
    boil: 3186,
    summary: "Silvery-white lustrous metal with a slight golden tinge.",
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    atomic_mass: 63.546,
    category: "transition metal",
    xpos: 11,
    ypos: 4,
    melt: 1357.77,
    boil: 2835,
    summary:
      "Soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    atomic_mass: 65.38,
    category: "transition metal",
    xpos: 12,
    ypos: 4,
    melt: 692.68,
    boil: 1180,
    summary: "Slightly brittle metal at room temperature.",
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    atomic_mass: 69.723,
    category: "post-transition metal",
    xpos: 13,
    ypos: 4,
    melt: 302.91,
    boil: 2477,
    summary: "Soft, silvery metal.",
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    atomic_mass: 72.63,
    category: "metalloid",
    xpos: 14,
    ypos: 4,
    melt: 1211.4,
    boil: 3106,
    summary: "Lustrous, hard-brittle, grayish-white metalloid.",
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    atomic_mass: 74.922,
    category: "metalloid",
    xpos: 15,
    ypos: 4,
    melt: 1090,
    boil: 887,
    summary:
      "Occurs in many minerals, usually in combination with sulfur and metals.",
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    atomic_mass: 78.96,
    category: "polyatomic nonmetal",
    xpos: 16,
    ypos: 4,
    melt: 494,
    boil: 958,
    summary: "Found rarely as an elemental mineral.",
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    atomic_mass: 79.904,
    category: "diatomic nonmetal",
    xpos: 17,
    ypos: 4,
    melt: 265.8,
    boil: 332.0,
    summary: "Fuming red-brown liquid at room temperature.",
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    atomic_mass: 83.798,
    category: "noble gas",
    xpos: 18,
    ypos: 4,
    melt: 115.79,
    boil: 119.93,
    summary: "Colorless, odorless, tasteless noble gas.",
  },

  // Chu kỳ 5
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomic_mass: 85.468,
    category: "alkali metal",
    xpos: 1,
    ypos: 5,
    melt: 312.46,
    boil: 961,
    summary: "Very soft, silvery-white metal.",
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    atomic_mass: 87.62,
    category: "alkaline earth metal",
    xpos: 2,
    ypos: 5,
    melt: 1050,
    boil: 1655,
    summary: "Highly reactive, chemically similar to calcium.",
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    atomic_mass: 88.906,
    category: "transition metal",
    xpos: 3,
    ypos: 5,
    melt: 1799,
    boil: 3609,
    summary: "Silvery-metallic transition metal.",
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomic_mass: 91.224,
    category: "transition metal",
    xpos: 4,
    ypos: 5,
    melt: 2128,
    boil: 4682,
    summary: "Lustrous, grey-white, strong transition metal.",
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    atomic_mass: 92.906,
    category: "transition metal",
    xpos: 5,
    ypos: 5,
    melt: 2750,
    boil: 5017,
    summary: "Light grey, crystalline, and ductile transition metal.",
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomic_mass: 95.95,
    category: "transition metal",
    xpos: 6,
    ypos: 5,
    melt: 2896,
    boil: 4912,
    summary: "Does not occur naturally as a free metal on Earth.",
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    atomic_mass: 98,
    category: "transition metal",
    xpos: 7,
    ypos: 5,
    melt: 2430,
    boil: 4538,
    summary: "The lowest atomic number element without any stable isotopes.",
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomic_mass: 101.07,
    category: "transition metal",
    xpos: 8,
    ypos: 5,
    melt: 2607,
    boil: 4423,
    summary: "Rare transition metal belonging to the platinum group.",
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomic_mass: 102.91,
    category: "transition metal",
    xpos: 9,
    ypos: 5,
    melt: 2237,
    boil: 3968,
    summary: "Rare, silvery-white, hard, chemically inert transition metal.",
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    atomic_mass: 106.42,
    category: "transition metal",
    xpos: 10,
    ypos: 5,
    melt: 1828.05,
    boil: 3236,
    summary: "Rare and lustrous silvery-white metal.",
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    atomic_mass: 107.87,
    category: "transition metal",
    xpos: 11,
    ypos: 5,
    melt: 1234.93,
    boil: 2435,
    summary: "Soft, white, lustrous transition metal.",
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomic_mass: 112.41,
    category: "transition metal",
    xpos: 12,
    ypos: 5,
    melt: 594.22,
    boil: 1040,
    summary: "Soft, bluish-white metal.",
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    atomic_mass: 114.82,
    category: "post-transition metal",
    xpos: 13,
    ypos: 5,
    melt: 429.75,
    boil: 2345,
    summary: "Post-transition metal.",
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    atomic_mass: 118.71,
    category: "post-transition metal",
    xpos: 14,
    ypos: 5,
    melt: 505.08,
    boil: 2875,
    summary: "Silvery metal that characteristically has a faint yellow hue.",
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    atomic_mass: 121.76,
    category: "metalloid",
    xpos: 15,
    ypos: 5,
    melt: 903.78,
    boil: 1860,
    summary: "Lustrous gray metalloid.",
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    atomic_mass: 127.6,
    category: "metalloid",
    xpos: 16,
    ypos: 5,
    melt: 722.66,
    boil: 1261,
    summary: "Brittle, mildly toxic, rare, silver-white metalloid.",
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    atomic_mass: 126.9,
    category: "diatomic nonmetal",
    xpos: 17,
    ypos: 5,
    melt: 386.85,
    boil: 457.4,
    summary: "The heaviest of the stable halogens.",
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    atomic_mass: 131.29,
    category: "noble gas",
    xpos: 18,
    ypos: 5,
    melt: 161.4,
    boil: 165.0,
    summary: "Colorless, dense, odorless noble gas.",
  },

  // Chu kỳ 6
  {
    number: 55,
    symbol: "Cs",
    name: "Caesium",
    atomic_mass: 132.91,
    category: "alkali metal",
    xpos: 1,
    ypos: 6,
    melt: 301.7,
    boil: 944,
    summary: "Soft, silvery-gold alkali metal with a melting point of 28.5 °C.",
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    atomic_mass: 137.33,
    category: "alkaline earth metal",
    xpos: 2,
    ypos: 6,
    melt: 1000,
    boil: 2170,
    summary: "Soft, silvery alkaline earth metal.",
  },
  // Lanthanides (57-71)
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    atomic_mass: 138.91,
    category: "lanthanide",
    xpos: 3,
    ypos: 9,
    melt: 1193,
    boil: 3737,
    summary: "Silvery-white metallic element.",
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    atomic_mass: 140.12,
    category: "lanthanide",
    xpos: 4,
    ypos: 9,
    melt: 1068,
    boil: 3716,
    summary: "Soft, ductile, and silvery-white metal.",
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomic_mass: 140.91,
    category: "lanthanide",
    xpos: 5,
    ypos: 9,
    melt: 1208,
    boil: 3793,
    summary: "Soft, silvery, malleable and ductile metal.",
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomic_mass: 144.24,
    category: "lanthanide",
    xpos: 6,
    ypos: 9,
    melt: 1297,
    boil: 3347,
    summary: "Soft silvery metal that tarnishes in air.",
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    atomic_mass: 145,
    category: "lanthanide",
    xpos: 7,
    ypos: 9,
    melt: 1315,
    boil: 3273,
    summary: "All of its isotopes are radioactive.",
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    atomic_mass: 150.36,
    category: "lanthanide",
    xpos: 8,
    ypos: 9,
    melt: 1345,
    boil: 2067,
    summary: "Moderately hard metal, silvery-white.",
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    atomic_mass: 151.96,
    category: "lanthanide",
    xpos: 9,
    ypos: 9,
    melt: 1099,
    boil: 1802,
    summary: "The most reactive lanthanide.",
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomic_mass: 157.25,
    category: "lanthanide",
    xpos: 10,
    ypos: 9,
    melt: 1585,
    boil: 3546,
    summary: "Silvery-white metal, malleable and ductile.",
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    atomic_mass: 158.93,
    category: "lanthanide",
    xpos: 11,
    ypos: 9,
    melt: 1629,
    boil: 3503,
    summary: "Silvery-white, rare earth metal.",
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomic_mass: 162.5,
    category: "lanthanide",
    xpos: 12,
    ypos: 9,
    melt: 1680,
    boil: 2840,
    summary: "Rare earth element with a metallic silver luster.",
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    atomic_mass: 164.93,
    category: "lanthanide",
    xpos: 13,
    ypos: 9,
    melt: 1734,
    boil: 2993,
    summary: "Relatively soft and malleable element.",
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    atomic_mass: 167.26,
    category: "lanthanide",
    xpos: 14,
    ypos: 9,
    melt: 1802,
    boil: 3141,
    summary: "Silvery-white solid metal when artificially isolated.",
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    atomic_mass: 168.93,
    category: "lanthanide",
    xpos: 15,
    ypos: 9,
    melt: 1818,
    boil: 2223,
    summary: "The least abundant of the lanthanides.",
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomic_mass: 173.05,
    category: "lanthanide",
    xpos: 16,
    ypos: 9,
    melt: 1097,
    boil: 1469,
    summary: "Soft, malleable and ductile chemical element.",
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomic_mass: 174.97,
    category: "lanthanide",
    xpos: 17,
    ypos: 9,
    melt: 1925,
    boil: 3675,
    summary: "Silvery white metal, resists corrosion in dry air.",
  },
  // End Lanthanides (quay lai chu ky 6)
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomic_mass: 178.49,
    category: "transition metal",
    xpos: 4,
    ypos: 6,
    melt: 2506,
    boil: 4876,
    summary: "Lustrous, silvery gray, tetravalent transition metal.",
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomic_mass: 180.95,
    category: "transition metal",
    xpos: 5,
    ypos: 6,
    melt: 3290,
    boil: 5731,
    summary: "Hard, blue-gray, lustrous transition metal.",
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    atomic_mass: 183.84,
    category: "transition metal",
    xpos: 6,
    ypos: 6,
    melt: 3695,
    boil: 5828,
    summary: "Hard, rare metal under standard conditions.",
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    atomic_mass: 186.21,
    category: "transition metal",
    xpos: 7,
    ypos: 6,
    melt: 3459,
    boil: 5869,
    summary: "Silvery-white, heavy, third-row transition metal.",
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    atomic_mass: 190.23,
    category: "transition metal",
    xpos: 8,
    ypos: 6,
    melt: 3306,
    boil: 5285,
    summary: "Hard, brittle, bluish-white transition metal.",
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    atomic_mass: 192.22,
    category: "transition metal",
    xpos: 9,
    ypos: 6,
    melt: 2719,
    boil: 4701,
    summary: "Very hard, brittle, silvery-white transition metal.",
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    atomic_mass: 195.08,
    category: "transition metal",
    xpos: 10,
    ypos: 6,
    melt: 2041.4,
    boil: 4098,
    summary: "Dense, malleable, ductile, highly unreactive.",
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    atomic_mass: 196.97,
    category: "transition metal",
    xpos: 11,
    ypos: 6,
    melt: 1337.33,
    boil: 3129,
    summary: "Bright, slightly reddish yellow, dense, soft, malleable.",
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    atomic_mass: 200.59,
    category: "transition metal",
    xpos: 12,
    ypos: 6,
    melt: 234.32,
    boil: 629.88,
    summary: "Heavy, silvery d-block element, liquid at STP.",
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    atomic_mass: 204.38,
    category: "post-transition metal",
    xpos: 13,
    ypos: 6,
    melt: 577,
    boil: 1746,
    summary: "Soft gray post-transition metal.",
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    atomic_mass: 207.2,
    category: "post-transition metal",
    xpos: 14,
    ypos: 6,
    melt: 600.61,
    boil: 2022,
    summary: "Heavy metal that is denser than most common materials.",
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomic_mass: 208.98,
    category: "post-transition metal",
    xpos: 15,
    ypos: 6,
    melt: 544.7,
    boil: 1837,
    summary: "Pentavalent post-transition metal.",
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    atomic_mass: 209,
    category: "post-transition metal",
    xpos: 16,
    ypos: 6,
    melt: 527,
    boil: 1235,
    summary: "Rare and highly radioactive metal.",
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    atomic_mass: 210,
    category: "metalloid",
    xpos: 17,
    ypos: 6,
    melt: 575,
    boil: 610,
    summary: "Rare radioactive chemical element.",
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    atomic_mass: 222,
    category: "noble gas",
    xpos: 18,
    ypos: 6,
    melt: 202,
    boil: 211.3,
    summary: "Radioactive, colorless, odorless, tasteless noble gas.",
  },

  // Chu kỳ 7
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    atomic_mass: 223,
    category: "alkali metal",
    xpos: 1,
    ypos: 7,
    melt: 300,
    boil: 950,
    summary: "Highly radioactive.",
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    atomic_mass: 226,
    category: "alkaline earth metal",
    xpos: 2,
    ypos: 7,
    melt: 973,
    boil: 2010,
    summary: "Pure white alkaline earth metal.",
  },
  // Actinides (89-103)
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    atomic_mass: 227,
    category: "actinide",
    xpos: 3,
    ypos: 10,
    melt: 1323,
    boil: 3471,
    summary: "Silvery-white radioactive metallic element.",
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    atomic_mass: 232.04,
    category: "actinide",
    xpos: 4,
    ypos: 10,
    melt: 2115,
    boil: 5061,
    summary: "Weakly radioactive metallic chemical element.",
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomic_mass: 231.04,
    category: "actinide",
    xpos: 5,
    ypos: 10,
    melt: 1841,
    boil: 4300,
    summary: "Dense, silvery-gray material.",
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    atomic_mass: 238.03,
    category: "actinide",
    xpos: 6,
    ypos: 10,
    melt: 1405.3,
    boil: 4404,
    summary: "Silvery-white metal in the actinide series.",
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    atomic_mass: 237,
    category: "actinide",
    xpos: 7,
    ypos: 10,
    melt: 917,
    boil: 4273,
    summary: "Radioactive actinide metal.",
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomic_mass: 244,
    category: "actinide",
    xpos: 8,
    ypos: 10,
    melt: 912.5,
    boil: 3501,
    summary: "Radioactive chemical element.",
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    atomic_mass: 243,
    category: "actinide",
    xpos: 9,
    ypos: 10,
    melt: 1449,
    boil: 2880,
    summary: "Synthetic radioactive chemical element.",
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    atomic_mass: 247,
    category: "actinide",
    xpos: 10,
    ypos: 10,
    melt: 1613,
    boil: 3383,
    summary: "Hard, dense, silvery metal.",
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomic_mass: 247,
    category: "actinide",
    xpos: 11,
    ypos: 10,
    melt: 1259,
    boil: 2900,
    summary: "Soft, silvery-white radioactive metal.",
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    atomic_mass: 251,
    category: "actinide",
    xpos: 12,
    ypos: 10,
    melt: 1173,
    boil: 1743,
    summary: "Radioactive metallic chemical element.",
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomic_mass: 252,
    category: "actinide",
    xpos: 13,
    ypos: 10,
    melt: 1133,
    boil: 1269,
    summary: "Soft, silvery, paramagnetic metal.",
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    atomic_mass: 257,
    category: "actinide",
    xpos: 14,
    ypos: 10,
    melt: 1800,
    boil: null,
    summary: "Synthetic element.",
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomic_mass: 258,
    category: "actinide",
    xpos: 15,
    ypos: 10,
    melt: 1100,
    boil: null,
    summary: "Synthetic element.",
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    atomic_mass: 259,
    category: "actinide",
    xpos: 16,
    ypos: 10,
    melt: 1100,
    boil: null,
    summary: "Synthetic element.",
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomic_mass: 266,
    category: "actinide",
    xpos: 17,
    ypos: 10,
    melt: 1900,
    boil: null,
    summary: "Synthetic radioactive element.",
  },
  // End Actinides (quay lai chu ky 7)
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomic_mass: 267,
    category: "transition metal",
    xpos: 4,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    atomic_mass: 268,
    category: "transition metal",
    xpos: 5,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomic_mass: 269,
    category: "transition metal",
    xpos: 6,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomic_mass: 270,
    category: "transition metal",
    xpos: 7,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    atomic_mass: 277,
    category: "transition metal",
    xpos: 8,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomic_mass: 278,
    category: "unknown",
    xpos: 9,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomic_mass: 281,
    category: "unknown",
    xpos: 10,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomic_mass: 282,
    category: "unknown",
    xpos: 11,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomic_mass: 285,
    category: "transition metal",
    xpos: 12,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomic_mass: 286,
    category: "unknown",
    xpos: 13,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomic_mass: 289,
    category: "post-transition metal",
    xpos: 14,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomic_mass: 290,
    category: "unknown",
    xpos: 15,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomic_mass: 293,
    category: "unknown",
    xpos: 16,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomic_mass: 294,
    category: "unknown",
    xpos: 17,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    atomic_mass: 294,
    category: "noble gas",
    xpos: 18,
    ypos: 7,
    melt: null,
    boil: null,
    summary: "Synthetic.",
  },
];

export const CATEGORY_STYLES: Record<
  string,
  { bg: string; text: string; border: string; glow: string }
> = {
  "diatomic nonmetal": {
    bg: "bg-blue-500/20",
    border: "border-blue-500",
    text: "text-blue-400",
    glow: "shadow-blue-500/50",
  },
  "noble gas": {
    bg: "bg-purple-500/20",
    border: "border-purple-500",
    text: "text-purple-400",
    glow: "shadow-purple-500/50",
  },
  "alkali metal": {
    bg: "bg-red-500/20",
    border: "border-red-500",
    text: "text-red-400",
    glow: "shadow-red-500/50",
  },
  "alkaline earth metal": {
    bg: "bg-orange-500/20",
    border: "border-orange-500",
    text: "text-orange-400",
    glow: "shadow-orange-500/50",
  },
  metalloid: {
    bg: "bg-teal-500/20",
    border: "border-teal-500",
    text: "text-teal-400",
    glow: "shadow-teal-500/50",
  },
  "polyatomic nonmetal": {
    bg: "bg-green-500/20",
    border: "border-green-500",
    text: "text-green-400",
    glow: "shadow-green-500/50",
  },
  "transition metal": {
    bg: "bg-pink-500/20",
    border: "border-pink-500",
    text: "text-pink-400",
    glow: "shadow-pink-500/50",
  },
  "post-transition metal": {
    bg: "bg-gray-500/20",
    border: "border-gray-400",
    text: "text-gray-300",
    glow: "shadow-gray-500/50",
  },
  lanthanide: {
    bg: "bg-indigo-500/20",
    border: "border-indigo-500",
    text: "text-indigo-300",
    glow: "shadow-indigo-500/50",
  },
  actinide: {
    bg: "bg-rose-500/20",
    border: "border-rose-500",
    text: "text-rose-300",
    glow: "shadow-rose-500/50",
  },
  unknown: {
    bg: "bg-slate-700/50",
    border: "border-slate-600",
    text: "text-slate-400",
    glow: "shadow-slate-500/50",
  },
};
