import {
  Star,
  Atom,
  Layers,
  Smartphone,
  Box,
  Settings,
  PenTool,
  Database,
  Shield,
  Command,
  Server,
  Hash,
} from "lucide-react";
import { CategoryId, Library } from "../types/library_type";

// --- CATEGORIES ---
export const CATEGORIES: {
  id: CategoryId;
  label: string;
  icon: any;
  color: string;
}[] = [
  { id: "favorites", label: "Yêu thích", icon: Star, color: "text-yellow-400" },
  { id: "react", label: "React / Next", icon: Atom, color: "text-sky-400" },
  { id: "vue", label: "Vue / Nuxt", icon: Layers, color: "text-emerald-400" },
  {
    id: "node",
    label: "Node / Backend",
    icon: Server,
    color: "text-green-500",
  },
  { id: "python", label: "Python / AI", icon: Hash, color: "text-yellow-400" },
  { id: "flutter", label: "Flutter", icon: Smartphone, color: "text-blue-400" },
  { id: "go", label: "Golang", icon: Box, color: "text-cyan-400" },
  { id: "rust", label: "Rust", icon: Settings, color: "text-orange-400" },
  { id: "css", label: "CSS / UI", icon: PenTool, color: "text-pink-400" },
  { id: "db", label: "Database", icon: Database, color: "text-purple-400" },
  { id: "test", label: "Testing", icon: Shield, color: "text-red-400" },
  { id: "utils", label: "Utilities", icon: Command, color: "text-slate-400" },
];

// --- STATIC DATA ---
export const LIBRARIES: Library[] = [
  // === REACT ECOSYSTEM ===
  {
    id: "r1",
    name: "React Router",
    cmdName: "react-router-dom",
    desc: "Standard routing library",
    category: "react",
    url: "https://reactrouter.com/",
  },
  {
    id: "r2",
    name: "TanStack Query",
    cmdName: "@tanstack/react-query",
    desc: "Powerful async state management",
    category: "react",
    url: "https://tanstack.com/query",
  },
  {
    id: "r3",
    name: "Zustand",
    cmdName: "zustand",
    desc: "Bear necessities state management",
    category: "react",
    url: "https://github.com/pmndrs/zustand",
  },
  {
    id: "r4",
    name: "Redux Toolkit",
    cmdName: "@reduxjs/toolkit react-redux",
    desc: "Standard Redux logic",
    category: "react",
    url: "https://redux-toolkit.js.org/",
  },
  {
    id: "r5",
    name: "Recoil",
    cmdName: "recoil",
    desc: "Atomic state management",
    category: "react",
    url: "https://recoiljs.org/",
  },
  {
    id: "r6",
    name: "Framer Motion",
    cmdName: "framer-motion",
    desc: "Production-ready animation",
    category: "react",
    url: "https://www.framer.com/motion/",
  },
  {
    id: "r7",
    name: "React Hook Form",
    cmdName: "react-hook-form",
    desc: "Performant, flexible forms",
    category: "react",
    url: "https://react-hook-form.com/",
  },
  {
    id: "r8",
    name: "Next.js",
    cmdName: "next",
    desc: "The React Framework",
    category: "react",
    url: "https://nextjs.org/",
  },
  {
    id: "r9",
    name: "Lucide React",
    cmdName: "lucide-react",
    desc: "Beautiful & consistent icons",
    category: "react",
    url: "https://lucide.dev/",
  },
  {
    id: "r10",
    name: "React Icons",
    cmdName: "react-icons",
    desc: "SVG icons from popular sets",
    category: "react",
    url: "https://react-icons.github.io/react-icons/",
  },
  {
    id: "r11",
    name: "React Use",
    cmdName: "react-use",
    desc: "Collection of essential hooks",
    category: "react",
    url: "https://github.com/streamich/react-use",
  },
  {
    id: "r12",
    name: "Formik",
    cmdName: "formik yup",
    desc: "Build forms without tears",
    category: "react",
    url: "https://formik.org/",
  },

  // === VUE / NUXT ===
  {
    id: "v1",
    name: "Vue Router",
    cmdName: "vue-router",
    desc: "Official router for Vue",
    category: "vue",
    url: "https://router.vuejs.org/",
  },
  {
    id: "v2",
    name: "Pinia",
    cmdName: "pinia",
    desc: "Intuitive store for Vue",
    category: "vue",
    url: "https://pinia.vuejs.org/",
  },
  {
    id: "v3",
    name: "Nuxt",
    cmdName: "nuxt",
    desc: "The Intuitive Web Framework",
    category: "vue",
    url: "https://nuxt.com/",
  },
  {
    id: "v4",
    name: "VueUse",
    cmdName: "@vueuse/core",
    desc: "Collection of essential Vue utilities",
    category: "vue",
    url: "https://vueuse.org/",
  },
  {
    id: "v5",
    name: "Vite",
    cmdName: "vite",
    desc: "Next Generation Frontend Tooling",
    category: "vue",
    url: "https://vitejs.dev/",
    isDev: true,
  },

  // === NODE / BACKEND ===
  {
    id: "n1",
    name: "Express",
    cmdName: "express",
    desc: "Fast, unopinionated web framework",
    category: "node",
    url: "https://expressjs.com/",
  },
  {
    id: "n2",
    name: "NestJS",
    cmdName: "@nestjs/core @nestjs/common",
    desc: "Progressive Node.js framework",
    category: "node",
    url: "https://nestjs.com/",
  },
  {
    id: "n3",
    name: "Fastify",
    cmdName: "fastify",
    desc: "Fast and low overhead framework",
    category: "node",
    url: "https://fastify.io/",
  },
  {
    id: "n4",
    name: "Socket.IO",
    cmdName: "socket.io",
    desc: "Bidirectional events",
    category: "node",
    url: "https://socket.io/",
  },
  {
    id: "n5",
    name: "Zod",
    cmdName: "zod",
    desc: "TypeScript schema validation",
    category: "node",
    url: "https://zod.dev/",
  },
  {
    id: "n6",
    name: "JsonWebToken",
    cmdName: "jsonwebtoken",
    desc: "JWT implementation",
    category: "node",
    url: "https://github.com/auth0/node-jsonwebtoken",
  },
  {
    id: "n7",
    name: "Bcrypt",
    cmdName: "bcrypt",
    desc: "Library to help hash passwords",
    category: "node",
    url: "https://www.npmjs.com/package/bcrypt",
  },
  {
    id: "n8",
    name: "Dotenv",
    cmdName: "dotenv",
    desc: "Load environment variables",
    category: "node",
    url: "https://github.com/motdotla/dotenv",
  },
  {
    id: "n9",
    name: "Nodemon",
    cmdName: "nodemon",
    desc: "Auto restart node server",
    category: "node",
    url: "https://nodemon.io/",
    isDev: true,
  },
  {
    id: "n10",
    name: "Multer",
    cmdName: "multer",
    desc: "Middleware for handling multipart/form-data",
    category: "node",
    url: "https://github.com/expressjs/multer",
  },

  // === CSS / UI ===
  {
    id: "c1",
    name: "Tailwind CSS",
    cmdName: "tailwindcss postcss autoprefixer",
    desc: "Utility-first CSS framework",
    category: "css",
    url: "https://tailwindcss.com/",
    isDev: true,
  },
  {
    id: "c2",
    name: "Sass",
    cmdName: "sass",
    desc: "CSS with superpowers",
    category: "css",
    url: "https://sass-lang.com/",
    isDev: true,
  },
  {
    id: "c3",
    name: "Styled Components",
    cmdName: "styled-components",
    desc: "Visual primitives for component age",
    category: "css",
    url: "https://styled-components.com/",
  },
  {
    id: "c4",
    name: "Emotion",
    cmdName: "@emotion/react @emotion/styled",
    desc: "CSS-in-JS library",
    category: "css",
    url: "https://emotion.sh/",
  },
  {
    id: "c5",
    name: "Material UI",
    cmdName: "@mui/material @emotion/react @emotion/styled",
    desc: "Material Design components",
    category: "css",
    url: "https://mui.com/",
  },
  {
    id: "c6",
    name: "Chakra UI",
    cmdName: "@chakra-ui/react @emotion/react @emotion/styled framer-motion",
    desc: "Modular & accessible component lib",
    category: "css",
    url: "https://chakra-ui.com/",
  },
  {
    id: "c7",
    name: "Ant Design",
    cmdName: "antd",
    desc: "Enterprise-class UI",
    category: "css",
    url: "https://ant.design/",
  },
  {
    id: "c8",
    name: "Shadcn UI",
    cmdName: "npx shadcn-ui@latest init",
    desc: "Beautifully designed components",
    category: "css",
    url: "https://ui.shadcn.com/",
  },
  {
    id: "c9",
    name: "Radix UI",
    cmdName: "@radix-ui/react-popover",
    desc: "Unstyled, accessible components",
    category: "css",
    url: "https://www.radix-ui.com/",
  },

  // === UTILS ===
  {
    id: "u1",
    name: "Lodash",
    cmdName: "lodash",
    desc: "Modern JavaScript utility library",
    category: "utils",
    url: "https://lodash.com/",
  },
  {
    id: "u2",
    name: "Axios",
    cmdName: "axios",
    desc: "Promise based HTTP client",
    category: "utils",
    url: "https://axios-http.com/",
  },
  {
    id: "u3",
    name: "Day.js",
    cmdName: "dayjs",
    desc: "2kB immutable date library",
    category: "utils",
    url: "https://day.js.org/",
  },
  {
    id: "u4",
    name: "Date-fns",
    cmdName: "date-fns",
    desc: "Modern JavaScript date utility",
    category: "utils",
    url: "https://date-fns.org/",
  },
  {
    id: "u5",
    name: "UUID",
    cmdName: "uuid",
    desc: "Generate RFC-compliant UUIDs",
    category: "utils",
    url: "https://github.com/uuidjs/uuid",
  },
  {
    id: "u6",
    name: "Classnames",
    cmdName: "classnames",
    desc: "Conditionally join classNames",
    category: "utils",
    url: "https://github.com/JedWatson/classnames",
  },
  {
    id: "u7",
    name: "Chalk",
    cmdName: "chalk",
    desc: "Terminal string styling",
    category: "utils",
    url: "https://github.com/chalk/chalk",
  },

  // === DATABASE ===
  {
    id: "d1",
    name: "Mongoose",
    cmdName: "mongoose",
    desc: "MongoDB object modeling",
    category: "db",
    url: "https://mongoosejs.com/",
  },
  {
    id: "d2",
    name: "Prisma",
    cmdName: "prisma",
    desc: "Next-generation ORM",
    category: "db",
    url: "https://www.prisma.io/",
    isDev: true,
  },
  {
    id: "d3",
    name: "TypeORM",
    cmdName: "typeorm reflect-metadata",
    desc: "ORM for TS and JS",
    category: "db",
    url: "https://typeorm.io/",
  },
  {
    id: "d4",
    name: "Sequelize",
    cmdName: "sequelize",
    desc: "Promise-based Node.js ORM",
    category: "db",
    url: "https://sequelize.org/",
  },
  {
    id: "d5",
    name: "Firebase",
    cmdName: "firebase",
    desc: "Firebase SDK",
    category: "db",
    url: "https://firebase.google.com/",
  },
  {
    id: "d6",
    name: "Supabase",
    cmdName: "@supabase/supabase-js",
    desc: "Open source Firebase alternative",
    category: "db",
    url: "https://supabase.com/",
  },

  // === TESTING ===
  {
    id: "t1",
    name: "Jest",
    cmdName: "jest",
    desc: "Delightful JavaScript Testing",
    category: "test",
    url: "https://jestjs.io/",
    isDev: true,
  },
  {
    id: "t2",
    name: "Vitest",
    cmdName: "vitest",
    desc: "Blazing Fast Unit Test Framework",
    category: "test",
    url: "https://vitest.dev/",
    isDev: true,
  },
  {
    id: "t3",
    name: "Cypress",
    cmdName: "cypress",
    desc: "Fast, easy and reliable E2E testing",
    category: "test",
    url: "https://www.cypress.io/",
    isDev: true,
  },
  {
    id: "t4",
    name: "Playwright",
    cmdName: "@playwright/test",
    desc: "Reliable end-to-end testing",
    category: "test",
    url: "https://playwright.dev/",
    isDev: true,
  },
  {
    id: "t5",
    name: "Testing Library",
    cmdName: "@testing-library/react",
    desc: "Simple and complete testing utilities",
    category: "test",
    url: "https://testing-library.com/",
    isDev: true,
  },

  // === PYTHON ===
  {
    id: "p1",
    name: "Pandas",
    cmdName: "pandas",
    desc: "Data analysis tool",
    category: "python",
    url: "https://pandas.pydata.org/",
  },
  {
    id: "p2",
    name: "NumPy",
    cmdName: "numpy",
    desc: "Scientific computing",
    category: "python",
    url: "https://numpy.org/",
  },
  {
    id: "p3",
    name: "FastAPI",
    cmdName: "fastapi uvicorn",
    desc: "High performance API",
    category: "python",
    url: "https://fastapi.tiangolo.com/",
  },
  {
    id: "p4",
    name: "Requests",
    cmdName: "requests",
    desc: "HTTP for Humans",
    category: "python",
    url: "https://pypi.org/project/requests/",
  },
  {
    id: "p5",
    name: "Django",
    cmdName: "django",
    desc: "High-level Python Web framework",
    category: "python",
    url: "https://www.djangoproject.com/",
  },
  {
    id: "p6",
    name: "Flask",
    cmdName: "flask",
    desc: "Lightweight WSGI web app framework",
    category: "python",
    url: "https://flask.palletsprojects.com/",
  },
  {
    id: "p7",
    name: "PyTorch",
    cmdName: "torch torchvision",
    desc: "Deep learning framework",
    category: "python",
    url: "https://pytorch.org/",
  },
  {
    id: "p8",
    name: "TensorFlow",
    cmdName: "tensorflow",
    desc: "End-to-end ML platform",
    category: "python",
    url: "https://www.tensorflow.org/",
  },
  {
    id: "p9",
    name: "Scikit-learn",
    cmdName: "scikit-learn",
    desc: "Machine Learning in Python",
    category: "python",
    url: "https://scikit-learn.org/",
  },
  {
    id: "p10",
    name: "OpenCV",
    cmdName: "opencv-python",
    desc: "Computer Vision Library",
    category: "python",
    url: "https://opencv.org/",
  },

  // === FLUTTER ===
  {
    id: "f1",
    name: "Provider",
    cmdName: "provider",
    desc: "State management",
    category: "flutter",
    url: "https://pub.dev/packages/provider",
  },
  {
    id: "f2",
    name: "Dio",
    cmdName: "dio",
    desc: "Powerful Http client",
    category: "flutter",
    url: "https://pub.dev/packages/dio",
  },
  {
    id: "f3",
    name: "Go Router",
    cmdName: "go_router",
    desc: "Declarative routing",
    category: "flutter",
    url: "https://pub.dev/packages/go_router",
  },
  {
    id: "f4",
    name: "GetX",
    cmdName: "get",
    desc: "Extra-light and powerful solution",
    category: "flutter",
    url: "https://pub.dev/packages/get",
  },
  {
    id: "f5",
    name: "Bloc",
    cmdName: "flutter_bloc",
    desc: "Predictable state management",
    category: "flutter",
    url: "https://pub.dev/packages/flutter_bloc",
  },
  {
    id: "f6",
    name: "Riverpod",
    cmdName: "flutter_riverpod",
    desc: "Reactive caching and state binding",
    category: "flutter",
    url: "https://riverpod.dev/",
  },
  {
    id: "f7",
    name: "Hive",
    cmdName: "hive hive_flutter",
    desc: "Lightweight & blazing fast key-value DB",
    category: "flutter",
    url: "https://docs.hivedb.dev/",
  },
  {
    id: "f8",
    name: "Shared Prefs",
    cmdName: "shared_preferences",
    desc: "Simple data storage",
    category: "flutter",
    url: "https://pub.dev/packages/shared_preferences",
  },
  {
    id: "f9",
    name: "Google Fonts",
    cmdName: "google_fonts",
    desc: "Flutter package for Google Fonts",
    category: "flutter",
    url: "https://pub.dev/packages/google_fonts",
  },

  // === GO ===
  {
    id: "g1",
    name: "Gin",
    cmdName: "github.com/gin-gonic/gin",
    desc: "HTTP web framework",
    category: "go",
    url: "https://gin-gonic.com/",
  },
  {
    id: "g2",
    name: "GORM",
    cmdName: "gorm.io/gorm",
    desc: "The fantastic ORM library",
    category: "go",
    url: "https://gorm.io/",
  },
  {
    id: "g3",
    name: "Fiber",
    cmdName: "github.com/gofiber/fiber/v2",
    desc: "Express inspired web framework",
    category: "go",
    url: "https://gofiber.io/",
  },
  {
    id: "g4",
    name: "Echo",
    cmdName: "github.com/labstack/echo/v4",
    desc: "High performance, minimalist framework",
    category: "go",
    url: "https://echo.labstack.com/",
  },
  {
    id: "g5",
    name: "Viper",
    cmdName: "github.com/spf13/viper",
    desc: "Go configuration with fangs",
    category: "go",
    url: "https://github.com/spf13/viper",
  },

  // === RUST ===
  {
    id: "rs1",
    name: "Serde",
    cmdName: "serde",
    desc: "Serialization framework",
    category: "rust",
    url: "https://serde.rs/",
  },
  {
    id: "rs2",
    name: "Tokio",
    cmdName: "tokio",
    desc: "Asynchronous runtime",
    category: "rust",
    url: "https://tokio.rs/",
  },
  {
    id: "rs3",
    name: "Actix Web",
    cmdName: "actix-web",
    desc: "Powerful web framework",
    category: "rust",
    url: "https://actix.rs/",
  },
  {
    id: "rs4",
    name: "Clap",
    cmdName: "clap",
    desc: "Command Line Argument Parser",
    category: "rust",
    url: "https://clap.rs/",
  },
  {
    id: "rs5",
    name: "Rand",
    cmdName: "rand",
    desc: "Random number generation",
    category: "rust",
    url: "https://rust-random.github.io/book/",
  },
];
