import { useState, useMemo, useRef, useEffect, JSX } from "react";
import {
  Database,
  Plus,
  Minus,
  Share2,
  Key,
  Table as TableIcon,
  Search,
  Maximize,
  X,
  Focus,
  Cpu,
  FilePlus,
  FolderOpen,
  ArrowLeftRight,
  CheckSquare,
  Square,
  Trash2,
  Download,
  FileCode,
  FileJson,
  Image as ImageIcon,
  Upload,
  Edit3,
} from "lucide-react";

// --- TYPES & INTERFACES ---
interface Column {
  name: string;
  type: string;
  isPk?: boolean;
  isFk?: boolean;
  fkTargets?: string[];
}

interface TableData {
  id: string;
  name: string;
  position: { x: number; y: number };
  columns: Column[];
}

interface ERDiagram {
  id: string;
  name: string;
  tables: TableData[];
  lastModified: number;
}

// --- HELPER: COLOR GENERATOR ---
const generateStableColor = (str: string) => {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  const h = Math.abs(hash) % 360;
  return `hsl(${h}, 80%, 60%)`;
};

// --- HELPER: SQL GENERATOR ---
const generateSQL = (tables: TableData[]) => {
  let sql = `-- Generated by LocalDB Architect\n\n`;
  tables.forEach((table) => {
    sql += `CREATE TABLE ${table.name} (\n`;
    const cols = table.columns.map((col) => {
      let type = col.type.toUpperCase();
      if (type === "STRING") type = "VARCHAR(255)";
      if (type === "NUMBER") type = "INT";
      if (type === "BOOLEAN") type = "BOOLEAN";
      let line = `  ${col.name} ${type}`;
      if (col.isPk) line += " PRIMARY KEY";
      return line;
    });
    sql += cols.join(",\n");
    sql += `\n);\n\n`;
  });
  tables.forEach((table) => {
    table.columns.forEach((col) => {
      if (col.isFk && col.fkTargets) {
        col.fkTargets.forEach((targetId) => {
          const targetTable = tables.find((t) => t.id === targetId);
          if (targetTable) {
            sql += `ALTER TABLE ${table.name} ADD CONSTRAINT fk_${table.name}_${col.name}\n`;
            sql += `  FOREIGN KEY (${col.name}) REFERENCES ${targetTable.name}(id);\n\n`;
          }
        });
      }
    });
  });
  return sql;
};

// --- COMPONENT MAIN ---
export const ERDiagramModule = ({
  onSwitchToDatabase,
}: {
  onSwitchToDatabase?: () => void;
}) => {
  // --- STATE ---
  const [diagrams, setDiagrams] = useState<ERDiagram[]>([]);
  const [activeDiagramId, setActiveDiagramId] = useState<string | null>(null);

  // Modal State
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [diagramNameInput, setDiagramNameInput] = useState("");
  const [editingDiagramId, setEditingDiagramId] = useState<string | null>(null); // NEW: Track renaming

  // Editor State
  const [tables, setTables] = useState<TableData[]>([]);
  const [scale, setScale] = useState(1);
  const [offset, setOffset] = useState({ x: 0, y: 0 });

  // Interaction State
  const [isDraggingCanvas, setIsDraggingCanvas] = useState(false);
  const [draggingTableId, setDraggingTableId] = useState<string | null>(null);
  const [connectingSource, setConnectingSource] = useState<{
    tableId: string;
    colName: string;
    startX: number;
    startY: number;
  } | null>(null);
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });
  const [selectedConnection, setSelectedConnection] = useState<{
    sourceId: string;
    colName: string;
    targetId: string;
  } | null>(null);

  // Smart Features State
  const [searchQuery, setSearchQuery] = useState("");
  const [hoveredTable, setHoveredTable] = useState<string | null>(null);
  const [showMinimap, setShowMinimap] = useState(true);
  const [showExportMenu, setShowExportMenu] = useState(false);

  // Import Modal State
  const [showImportModal, setShowImportModal] = useState(false);
  const [dbTables, setDbTables] = useState<any[]>([]);
  const [selectedDbTables, setSelectedDbTables] = useState<string[]>([]);

  // Refs
  const dragStartRef = useRef({ x: 0, y: 0 });
  const canvasRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // --- INIT & PERSISTENCE ---
  useEffect(() => {
    const savedDiagrams = localStorage.getItem("dashboard_erd_diagrams");
    if (savedDiagrams) {
      setDiagrams(JSON.parse(savedDiagrams));
    } else {
      const newDiag = {
        id: "default",
        name: "My First ERD",
        tables: [],
        lastModified: Date.now(),
      };
      setDiagrams([newDiag]);
    }
  }, []);

  useEffect(() => {
    if (diagrams.length > 0) {
      localStorage.setItem("dashboard_erd_diagrams", JSON.stringify(diagrams));
    }
  }, [diagrams]);

  // Sync active diagram tables
  useEffect(() => {
    if (activeDiagramId) {
      const diag = diagrams.find((d) => d.id === activeDiagramId);
      if (diag) {
        setTables(diag.tables);
        setTimeout(() => {
          if (diag.tables.length > 0) handleCenterView(diag.tables);
          else {
            setOffset({ x: 0, y: 0 });
            setScale(1);
          }
        }, 100);
        setSelectedConnection(null);
      }
    }
  }, [activeDiagramId]);

  // Auto-save changes
  useEffect(() => {
    if (activeDiagramId) {
      setDiagrams((prev) =>
        prev.map((d) =>
          d.id === activeDiagramId
            ? { ...d, tables: tables, lastModified: Date.now() }
            : d
        )
      );
    }
  }, [tables]);

  // --- ACTIONS: TABLE MANAGEMENT ---
  const handleDeleteTable = (tableId: string) => {
    if (!confirm("Are you sure you want to delete this table?")) return;
    setTables((prev) => {
      const remainingTables = prev.filter((t) => t.id !== tableId);
      return remainingTables.map((t) => ({
        ...t,
        columns: t.columns.map((col) => {
          if (col.isFk && col.fkTargets) {
            const newTargets = col.fkTargets.filter((tid) => tid !== tableId);
            return {
              ...col,
              fkTargets: newTargets,
              isFk: newTargets.length > 0,
            };
          }
          return col;
        }),
      }));
    });
    if (hoveredTable === tableId) setHoveredTable(null);
  };

  // --- ACTIONS: DIAGRAM (NEW: SAVE/RENAME) ---
  const handleOpenCreateModal = () => {
    setEditingDiagramId(null);
    setDiagramNameInput("");
    setShowCreateModal(true);
  };

  const handleOpenRenameModal = (diagram: ERDiagram, e: React.MouseEvent) => {
    e.stopPropagation();
    setEditingDiagramId(diagram.id);
    setDiagramNameInput(diagram.name);
    setShowCreateModal(true);
  };

  const handleSaveDiagram = () => {
    if (!diagramNameInput.trim()) return;

    if (editingDiagramId) {
      // RENAME
      setDiagrams((prev) =>
        prev.map((d) =>
          d.id === editingDiagramId
            ? { ...d, name: diagramNameInput, lastModified: Date.now() }
            : d
        )
      );
    } else {
      // CREATE NEW
      const newDiag: ERDiagram = {
        id: Date.now().toString(),
        name: diagramNameInput,
        tables: [],
        lastModified: Date.now(),
      };
      setDiagrams([...diagrams, newDiag]);
      setActiveDiagramId(newDiag.id);
    }
    setShowCreateModal(false);
    setDiagramNameInput("");
    setEditingDiagramId(null);
  };

  const deleteDiagram = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (confirm("Delete this diagram?")) {
      setDiagrams((prev) => prev.filter((d) => d.id !== id));
      if (activeDiagramId === id) setActiveDiagramId(null);
    }
  };

  // --- ACTIONS: EXPORT / IMPORT ---
  const handleExportJSON = () => {
    if (!activeDiagramId) return;
    const diag = diagrams.find((d) => d.id === activeDiagramId);
    if (!diag) return;
    const dataStr =
      "data:text/json;charset=utf-8," +
      encodeURIComponent(JSON.stringify(diag));
    const downloadAnchorNode = document.createElement("a");
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `${diag.name}.json`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
    setShowExportMenu(false);
  };

  const handleExportSQL = () => {
    const sql = generateSQL(tables);
    const dataStr = "data:text/sql;charset=utf-8," + encodeURIComponent(sql);
    const downloadAnchorNode = document.createElement("a");
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `schema.sql`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
    setShowExportMenu(false);
  };

  const handleExportImage = () => {
    if (!canvasRef.current) return;
    const svgOriginal = canvasRef.current.querySelector("svg");
    if (!svgOriginal) return;
    const svgClone = svgOriginal.cloneNode(true) as SVGElement;

    let minX = Infinity,
      minY = Infinity,
      maxX = -Infinity,
      maxY = -Infinity;
    tables.forEach((t) => {
      if (t.position.x < minX) minX = t.position.x;
      if (t.position.y < minY) minY = t.position.y;
      if (t.position.x + 260 > maxX) maxX = t.position.x + 260;
      if (t.position.y + 40 + t.columns.length * 28 > maxY)
        maxY = t.position.y + 40 + t.columns.length * 28;
    });
    const padding = 50;
    const width = maxX - minX + padding * 2;
    const height = maxY - minY + padding * 2;

    svgClone.setAttribute("width", width.toString());
    svgClone.setAttribute("height", height.toString());
    svgClone.setAttribute(
      "viewBox",
      `${minX - padding} ${minY - padding} ${width} ${height}`
    );
    svgClone.style.transform = "";

    const tablesGroup = document.createElementNS(
      "http://www.w3.org/2000/svg",
      "g"
    );
    tables.forEach((t) => {
      const fo = document.createElementNS(
        "http://www.w3.org/2000/svg",
        "foreignObject"
      );
      fo.setAttribute("x", t.position.x.toString());
      fo.setAttribute("y", t.position.y.toString());
      fo.setAttribute("width", "260");
      fo.setAttribute("height", (40 + t.columns.length * 28).toString());
      const html = `<div xmlns="http://www.w3.org/1999/xhtml" style="width:100%; height:100%; background:#1a1b1e; border:1px solid #3e3e42; border-radius:8px; overflow:hidden; font-family:sans-serif; color:#cbd5e1;"><div style="height:36px; background:#252526; border-bottom:1px solid #3e3e42; display:flex; align-items:center; padding:0 12px; font-weight:bold; font-size:12px; color:#fff;">${
        t.name
      }</div><div style="padding:4px 0;">${t.columns
        .map(
          (c) =>
            `<div style="display:flex; justify-content:space-between; padding:4px 12px; font-size:10px;"><div style="display:flex; gap:4px; align-items:center;">${
              c.isPk ? '<span style="color:#eab308">PK</span>' : ""
            }${
              c.isFk ? '<span style="color:#60a5fa">FK</span>' : ""
            }<span style="${
              c.isPk ? "font-weight:bold; color:white;" : "color:#cbd5e1"
            }">${c.name}</span></div><span style="color:#64748b;">${
              c.type
            }</span></div>`
        )
        .join("")}</div></div>`;
      fo.innerHTML = html;
      tablesGroup.appendChild(fo);
    });
    svgClone.appendChild(tablesGroup);

    const serializer = new XMLSerializer();
    const svgString = serializer.serializeToString(svgClone);
    const imgData =
      "data:image/svg+xml;charset=utf-8," + encodeURIComponent(svgString);
    const downloadAnchorNode = document.createElement("a");
    downloadAnchorNode.setAttribute("href", imgData);
    downloadAnchorNode.setAttribute("download", `er_diagram.svg`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
    setShowExportMenu(false);
  };

  const handleImportDiagram = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const importedDiag = JSON.parse(ev.target?.result as string);
        if (importedDiag.id && importedDiag.tables) {
          importedDiag.id = Date.now().toString();
          importedDiag.name = importedDiag.name + " (Imported)";
          setDiagrams((prev) => [...prev, importedDiag]);
          alert("Diagram imported successfully!");
        } else {
          alert("Invalid diagram file.");
        }
      } catch (err) {
        alert("Error reading file.");
      }
    };
    reader.readAsText(file);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  // --- ACTIONS: VIEW & LAYOUT ---
  const handleCenterView = (currentTables = tables) => {
    if (currentTables.length === 0) return;
    let minX = Infinity,
      minY = Infinity,
      maxX = -Infinity,
      maxY = -Infinity;
    currentTables.forEach((t) => {
      if (t.position.x < minX) minX = t.position.x;
      if (t.position.y < minY) minY = t.position.y;
      if (t.position.x + 260 > maxX) maxX = t.position.x + 260;
      if (t.position.y + 40 + t.columns.length * 28 > maxY)
        maxY = t.position.y + 40 + t.columns.length * 28;
    });
    const contentWidth = maxX - minX;
    const contentHeight = maxY - minY;
    if (canvasRef.current) {
      const { width, height } = canvasRef.current.getBoundingClientRect();
      const fitScaleX = width / (contentWidth + 100);
      const fitScaleY = height / (contentHeight + 100);
      const newScale = Math.min(Math.min(fitScaleX, fitScaleY), 1);
      setScale(parseFloat(newScale.toFixed(2)));
      const newOffsetX =
        (width - contentWidth * newScale) / 2 - minX * newScale;
      const newOffsetY =
        (height - contentHeight * newScale) / 2 - minY * newScale;
      setOffset({ x: newOffsetX, y: newOffsetY });
    }
  };

  const handleZoom = (delta: number) =>
    setScale((prev) =>
      parseFloat(Math.min(Math.max(prev + delta, 0.1), 3).toFixed(2))
    );
  const handleWheel = (e: React.WheelEvent) => handleZoom(-e.deltaY * 0.001);

  // --- ACTIONS: CONNECTION ---
  const handleDeleteConnection = () => {
    if (!selectedConnection) return;
    setTables((prev) =>
      prev.map((t) => {
        if (t.id === selectedConnection.sourceId) {
          return {
            ...t,
            columns: t.columns.map((c) =>
              c.name === selectedConnection.colName && c.fkTargets
                ? {
                    ...c,
                    fkTargets: c.fkTargets.filter(
                      (tid) => tid !== selectedConnection.targetId
                    ),
                    isFk:
                      c.fkTargets.filter(
                        (tid) => tid !== selectedConnection.targetId
                      ).length > 0,
                  }
                : c
            ),
          };
        }
        return t;
      })
    );
    setSelectedConnection(null);
  };

  // --- ACTIONS: IMPORT TABLES ---
  const handleOpenImport = () => {
    const rawDbTables = localStorage.getItem("dashboard_db_tables");
    if (rawDbTables) {
      setDbTables(JSON.parse(rawDbTables));
      setSelectedDbTables([]);
      setShowImportModal(true);
    } else {
      alert("No database tables found.");
    }
  };
  const toggleDbTableSelection = (id: string) => {
    setSelectedDbTables((prev) =>
      prev.includes(id) ? prev.filter((tid) => tid !== id) : [...prev, id]
    );
  };
  const executeImport = () => {
    const newTables: TableData[] = selectedDbTables
      .map((tid, idx) => {
        const dbTable = dbTables.find((t) => t.id === tid);
        if (!dbTable) return null;
        const cols = 4;
        const gapX = 300;
        const gapY = 300;
        return {
          id: dbTable.id,
          name: dbTable.name,
          position: tables.find((t) => t.id === tid)?.position || {
            x: 50 + (idx % cols) * gapX,
            y: 50 + Math.floor(idx / cols) * gapY,
          },
          columns: dbTable.columns.map((c: any) => ({
            name: c.name,
            type: c.type,
            isPk: c.isPrimary,
            isFk: c.name.endsWith("_id"),
            fkTargets: c.name.endsWith("_id")
              ? [c.name.replace("_id", "s")]
              : [],
          })),
        };
      })
      .filter((t) => t !== null) as TableData[];
    const mergedTables = [...tables];
    newTables.forEach((nt) => {
      const existIdx = mergedTables.findIndex((t) => t.id === nt.id);
      if (existIdx >= 0) mergedTables[existIdx].columns = nt.columns;
      else mergedTables.push(nt);
    });
    setTables(mergedTables);
    setShowImportModal(false);
    setTimeout(() => handleCenterView(mergedTables), 100);
  };

  // --- MOUSE HANDLERS ---
  const handleMouseDown = (e: React.MouseEvent, tableId?: string) => {
    if (tableId) {
      e.stopPropagation();
      setDraggingTableId(tableId);
    } else {
      setIsDraggingCanvas(true);
      setSelectedConnection(null);
      setShowExportMenu(false);
    }
    dragStartRef.current = { x: e.clientX, y: e.clientY };
  };
  const handleMouseMove = (e: React.MouseEvent) => {
    if (canvasRef.current) {
      const rect = canvasRef.current.getBoundingClientRect();
      setMousePos({
        x: (e.clientX - rect.left - offset.x) / scale,
        y: (e.clientY - rect.top - offset.y) / scale,
      });
    }
    if (draggingTableId) {
      const dx = (e.clientX - dragStartRef.current.x) / scale;
      const dy = (e.clientY - dragStartRef.current.y) / scale;
      setTables((prev) =>
        prev.map((t) =>
          t.id === draggingTableId
            ? { ...t, position: { x: t.position.x + dx, y: t.position.y + dy } }
            : t
        )
      );
      dragStartRef.current = { x: e.clientX, y: e.clientY };
    } else if (isDraggingCanvas) {
      const dx = e.clientX - dragStartRef.current.x;
      const dy = e.clientY - dragStartRef.current.y;
      setOffset((prev) => ({ x: prev.x + dx, y: prev.y + dy }));
      dragStartRef.current = { x: e.clientX, y: e.clientY };
    }
  };
  const handleMouseUp = () => {
    setDraggingTableId(null);
    setIsDraggingCanvas(false);
    setConnectingSource(null);
  };
  const handleColumnMouseDown = (
    e: React.MouseEvent,
    tableId: string,
    colName: string
  ) => {
    e.stopPropagation();
    e.preventDefault();
    const rect = (e.target as HTMLElement).getBoundingClientRect();
    const canvasRect = canvasRef.current!.getBoundingClientRect();
    setConnectingSource({
      tableId,
      colName,
      startX: (rect.right - canvasRect.left - offset.x) / scale,
      startY: (rect.top + rect.height / 2 - canvasRect.top - offset.y) / scale,
    });
  };
  const handleColumnMouseUp = (e: React.MouseEvent, targetTableId: string) => {
    e.stopPropagation();
    if (connectingSource && connectingSource.tableId !== targetTableId) {
      setTables((prev) =>
        prev.map((t) =>
          t.id === connectingSource.tableId
            ? {
                ...t,
                columns: t.columns.map((c) => {
                  if (c.name === connectingSource.colName) {
                    const currentTargets = c.fkTargets || [];
                    if (!currentTargets.includes(targetTableId))
                      return {
                        ...c,
                        isFk: true,
                        fkTargets: [...currentTargets, targetTableId],
                      };
                  }
                  return c;
                }),
              }
            : t
        )
      );
      setConnectingSource(null);
    }
  };

  // --- SMART PATH LOGIC ---
  const getSmartPath = (
    startX: number,
    startY: number,
    endX: number,
    endY: number
  ) => {
    const deltaX = endX - startX;
    const midX = startX + deltaX / 2;
    const r = 12;
    if (deltaX > 40)
      return `M ${startX} ${startY} L ${
        midX - r
      } ${startY} Q ${midX} ${startY} ${midX} ${
        startY + (endY > startY ? r : -r)
      } L ${midX} ${endY + (endY > startY ? -r : r)} Q ${midX} ${endY} ${
        midX + r
      } ${endY} L ${endX} ${endY}`;
    const safetyGap = 40;
    const loopY = Math.max(startY, endY) + 120;
    return `M ${startX} ${startY} L ${startX + safetyGap} ${startY} L ${
      startX + safetyGap
    } ${loopY - r} Q ${startX + safetyGap} ${loopY} ${
      startX + safetyGap - r
    } ${loopY} L ${endX - safetyGap + r} ${loopY} Q ${
      endX - safetyGap
    } ${loopY} ${endX - safetyGap} ${loopY - r} L ${
      endX - safetyGap
    } ${endY} L ${endX} ${endY}`;
  };

  // --- MEMOS ---
  const relatedTableIds = useMemo(() => {
    const ids = new Set<string>();
    if (!hoveredTable) return ids;
    ids.add(hoveredTable);
    const currentTable = tables.find((t) => t.id === hoveredTable);
    if (currentTable)
      currentTable.columns.forEach((col) => {
        col.fkTargets?.forEach((targetId) => ids.add(targetId));
      });
    tables.forEach((t) => {
      t.columns.forEach((col) => {
        if (col.fkTargets?.includes(hoveredTable)) ids.add(t.id);
      });
    });
    return ids;
  }, [hoveredTable, tables]);

  const filteredTables = useMemo(() => {
    if (!searchQuery) return tables;
    return tables.map((t) => ({
      ...t,
      isMatch:
        t.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.columns.some((c) =>
          c.name.toLowerCase().includes(searchQuery.toLowerCase())
        ),
    }));
  }, [tables, searchQuery]);

  const connections = useMemo(() => {
    const lines: JSX.Element[] = [];
    tables.forEach((source) => {
      source.columns.forEach((col, colIdx) => {
        if (col.isFk && col.fkTargets) {
          col.fkTargets.forEach((targetId) => {
            const target = tables.find((t) => t.id === targetId);
            if (target) {
              const startX = source.position.x + 260;
              const startY = source.position.y + 40 + colIdx * 28 + 14;
              const endX = target.position.x;
              const endY = target.position.y + 20;
              const isSelected =
                selectedConnection?.sourceId === source.id &&
                selectedConnection?.colName === col.name &&
                selectedConnection.targetId === target.id;
              const isDirectlyConnected =
                hoveredTable === source.id || hoveredTable === target.id;
              const connectionKey = `${source.id}-${target.id}`;
              const uniqueColor = generateStableColor(connectionKey);
              const strokeColor = isSelected
                ? "#ef4444"
                : isDirectlyConnected
                ? "#3b82f6"
                : uniqueColor;
              const opacityClass =
                isSelected || (hoveredTable && isDirectlyConnected)
                  ? "opacity-100 z-50"
                  : hoveredTable
                  ? "opacity-5"
                  : "opacity-60 hover:opacity-100";
              const strokeWidth = isSelected || isDirectlyConnected ? 3 : 1.5;
              const pathData = getSmartPath(startX, startY, endX, endY);
              const markerId = `arrow-${connectionKey}-${col.name}`;
              lines.push(
                <g
                  key={`${source.id}-${col.name}-${target.id}`}
                  className={`transition-all duration-300 ${opacityClass}`}
                  style={{ pointerEvents: "all" }}
                  onClick={(e) => {
                    e.stopPropagation();
                    setSelectedConnection({
                      sourceId: source.id,
                      colName: col.name,
                      targetId: target.id,
                    });
                  }}
                >
                  <path
                    d={pathData}
                    fill="none"
                    stroke="transparent"
                    strokeWidth="20"
                    className="cursor-pointer"
                  />
                  <path
                    d={pathData}
                    fill="none"
                    stroke="#0f1012"
                    strokeWidth={strokeWidth + 3}
                  />
                  <path
                    d={pathData}
                    fill="none"
                    stroke={strokeColor}
                    strokeWidth={strokeWidth}
                    markerEnd={`url(#${markerId})`}
                  />
                  <defs>
                    <marker
                      id={markerId}
                      markerWidth="10"
                      markerHeight="7"
                      refX="9"
                      refY="3.5"
                      orient="auto"
                    >
                      <polygon points="0 0, 10 3.5, 0 7" fill={strokeColor} />
                    </marker>
                  </defs>
                  {(isDirectlyConnected || isSelected) && (
                    <circle cx={startX} cy={startY} r="3" fill={strokeColor} />
                  )}
                </g>
              );
            }
          });
        }
      });
    });
    return lines;
  }, [tables, hoveredTable, selectedConnection]);

  // --- RENDER: DASHBOARD MODE ---
  if (!activeDiagramId) {
    return (
      <div className="h-full flex flex-col bg-[#1e1e1e] text-slate-300 font-sans p-4 md:p-8 overflow-y-auto">
        <input
          type="file"
          ref={fileInputRef}
          className="hidden"
          accept=".json"
          onChange={handleImportDiagram}
        />
        <div className="max-w-6xl mx-auto w-full">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
            <div>
              <h1 className="text-2xl font-bold text-white mb-1 flex items-center gap-3">
                <Database size={28} className="text-blue-500" /> ER Diagrams
              </h1>
              <p className="text-slate-500 text-sm">
                Visual database design tool.
              </p>
            </div>
            <div className="flex flex-wrap gap-3 w-full md:w-auto">
              {onSwitchToDatabase && (
                <button
                  onClick={onSwitchToDatabase}
                  className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2 border border-[#3e3e42] rounded-lg hover:bg-[#252526] transition-colors text-sm font-medium whitespace-nowrap"
                >
                  <ArrowLeftRight size={16} /> Database
                </button>
              )}
              <button
                onClick={() => fileInputRef.current?.click()}
                className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2 border border-[#3e3e42] rounded-lg hover:bg-[#252526] transition-colors text-sm font-medium"
              >
                <Upload size={16} /> Import File
              </button>
              <button
                onClick={handleOpenCreateModal}
                className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg shadow-lg transition-colors text-sm font-bold whitespace-nowrap"
              >
                <FilePlus size={16} /> New Diagram
              </button>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {diagrams.map((d) => (
              <div
                key={d.id}
                onClick={() => setActiveDiagramId(d.id)}
                className="bg-[#252526] border border-[#3e3e42] rounded-xl p-5 cursor-pointer hover:border-blue-500/50 hover:bg-[#2d2d2d] transition-all group relative flex flex-col h-40"
              >
                <div className="flex justify-between items-start mb-auto">
                  <div className="p-3 bg-blue-500/10 rounded-lg text-blue-400 group-hover:bg-blue-500 group-hover:text-white transition-colors">
                    <FolderOpen size={24} />
                  </div>
                  <div className="flex gap-1">
                    <button
                      onClick={(e) => handleOpenRenameModal(d, e)}
                      className="p-2 hover:bg-yellow-500/10 text-slate-500 hover:text-yellow-500 rounded-lg transition-colors"
                    >
                      <Edit3 size={16} />
                    </button>
                    <button
                      onClick={(e) => deleteDiagram(d.id, e)}
                      className="p-2 hover:bg-red-500/10 text-slate-500 hover:text-red-500 rounded-lg transition-colors"
                    >
                      <X size={16} />
                    </button>
                  </div>
                </div>
                <div>
                  <h3 className="font-bold text-lg text-white mb-1 truncate">
                    {d.name}
                  </h3>
                  <div className="flex items-center justify-between text-xs text-slate-500">
                    <span>{new Date(d.lastModified).toLocaleDateString()}</span>
                    <span className="flex items-center gap-1 bg-[#1e1e1e] px-2 py-1 rounded border border-[#3e3e42]">
                      <TableIcon size={10} /> {d.tables.length}
                    </span>
                  </div>
                </div>
              </div>
            ))}
            {diagrams.length === 0 && (
              <div className="col-span-full py-20 text-center text-slate-500 border-2 border-dashed border-[#3e3e42] rounded-xl">
                <p>No diagrams yet.</p>
              </div>
            )}
          </div>
        </div>
        {showCreateModal && (
          <div className="absolute inset-0 bg-black/80 z-50 flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in zoom-in-95">
            <div className="w-full max-w-sm bg-[#252526] border border-[#3e3e42] rounded-2xl shadow-2xl p-5">
              <h3 className="text-lg font-bold text-white mb-4">
                {editingDiagramId ? "Rename Diagram" : "New Diagram"}
              </h3>
              <input
                value={diagramNameInput}
                onChange={(e) => setDiagramNameInput(e.target.value)}
                placeholder="e.g. E-commerce Schema"
                autoFocus
                className="w-full bg-[#1e1e1e] border border-[#3e3e42] rounded-xl px-4 py-3 text-sm text-white mb-4 outline-none focus:border-blue-500"
                onKeyDown={(e) => e.key === "Enter" && handleSaveDiagram()}
              />
              <div className="flex gap-2">
                <button
                  onClick={() => setShowCreateModal(false)}
                  className="flex-1 py-2.5 rounded-xl bg-[#3e3e42] text-white text-sm font-bold hover:bg-[#4e4e52]"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveDiagram}
                  className="flex-1 py-2.5 rounded-xl bg-blue-600 text-white text-sm font-bold shadow-lg hover:bg-blue-500"
                >
                  Save
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  // --- RENDER: EDITOR MODE ---
  return (
    <div className="h-full flex flex-col bg-[#0f1012] text-slate-300 font-sans overflow-hidden relative">
      <div className="flex-none p-3 border-b border-[#2d2d2d] bg-[#1a1b1e] flex flex-col md:flex-row items-start md:items-center justify-between gap-3 z-30 shadow-md">
        <div className="flex items-center gap-4 w-full md:w-auto">
          <button
            onClick={() => setActiveDiagramId(null)}
            className="p-2 hover:bg-[#2d2d2d] rounded-lg text-slate-400 hover:text-white transition-colors"
          >
            <X size={18} />
          </button>
          <div className="flex items-center gap-2 font-bold text-white shrink-0">
            <span className="text-slate-500 hidden sm:inline">Diagram /</span>{" "}
            <span className="text-blue-400 max-w-[150px] truncate">
              {diagrams.find((d) => d.id === activeDiagramId)?.name}
            </span>
          </div>
          <div className="relative flex-1 md:w-64">
            <Search
              size={14}
              className="absolute left-3 top-2.5 text-slate-500"
            />
            <input
              type="text"
              placeholder="Search tables..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-[#0f1012] border border-[#2d2d2d] rounded-lg pl-9 pr-3 py-1.5 text-xs text-white focus:border-blue-500 outline-none"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery("")}
                className="absolute right-2 top-2 text-slate-500 hover:text-white"
              >
                <X size={14} />
              </button>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2 w-full md:w-auto justify-end relative">
          {selectedConnection && (
            <button
              onClick={handleDeleteConnection}
              className="flex items-center gap-2 px-3 py-1.5 bg-red-600/10 text-red-400 border border-red-600/20 hover:bg-red-600/20 rounded-lg text-xs font-bold transition-all animate-in fade-in"
            >
              <Trash2 size={14} /> Delete Link
            </button>
          )}
          <button
            onClick={handleOpenImport}
            className="flex items-center gap-2 px-3 py-1.5 bg-green-600/10 text-green-400 border border-green-600/20 hover:bg-green-600/20 rounded-lg text-xs font-bold transition-all whitespace-nowrap"
          >
            <Share2 size={14} />{" "}
            <span className="hidden sm:inline">Import</span>
          </button>
          <div className="relative">
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              className={`flex items-center gap-2 px-3 py-1.5 border rounded-lg text-xs font-bold transition-all ${
                showExportMenu
                  ? "bg-blue-600 text-white border-blue-600"
                  : "bg-[#0f1012] border-[#2d2d2d] text-slate-400 hover:text-white"
              }`}
            >
              <Download size={14} /> Export
            </button>
            {showExportMenu && (
              <>
                <div
                  className="fixed inset-0 z-40"
                  onClick={() => setShowExportMenu(false)}
                ></div>
                <div className="absolute right-0 top-full mt-2 w-48 bg-[#252526] border border-[#3e3e42] rounded-xl shadow-2xl z-50 overflow-hidden flex flex-col p-1 animate-in fade-in zoom-in-95">
                  <button
                    onClick={handleExportJSON}
                    className="flex items-center gap-3 px-3 py-2 text-xs font-medium text-slate-300 hover:bg-[#3e3e42] hover:text-white rounded-lg text-left"
                  >
                    <FileJson size={14} className="text-yellow-500" /> Export
                    JSON
                  </button>
                  <button
                    onClick={handleExportSQL}
                    className="flex items-center gap-3 px-3 py-2 text-xs font-medium text-slate-300 hover:bg-[#3e3e42] hover:text-white rounded-lg text-left"
                  >
                    <FileCode size={14} className="text-blue-500" /> Export SQL
                  </button>
                  <button
                    onClick={handleExportImage}
                    className="flex items-center gap-3 px-3 py-2 text-xs font-medium text-slate-300 hover:bg-[#3e3e42] hover:text-white rounded-lg text-left"
                  >
                    <ImageIcon size={14} className="text-purple-500" /> Export
                    SVG
                  </button>
                </div>
              </>
            )}
          </div>
          <div className="flex bg-[#0f1012] rounded-lg p-1 border border-[#2d2d2d]">
            <button
              onClick={() => handleZoom(-0.1)}
              className="p-1.5 hover:bg-[#2d2d2d] rounded text-slate-400 hover:text-white"
            >
              <Minus size={14} />
            </button>
            <span className="px-2 text-xs flex items-center font-mono text-slate-300 w-12 justify-center">
              {Math.round(scale * 100)}%
            </span>
            <button
              onClick={() => handleZoom(0.1)}
              className="p-1.5 hover:bg-[#2d2d2d] rounded text-slate-400 hover:text-white"
            >
              <Plus size={14} />
            </button>
          </div>
          <button
            onClick={() => handleCenterView()}
            className="p-2 hover:bg-[#2d2d2d] rounded-lg border border-transparent hover:border-[#2d2d2d] text-slate-400 hover:text-blue-400"
            title="Auto Center"
          >
            <Cpu size={18} />
          </button>
        </div>
      </div>

      <div
        ref={canvasRef}
        className="flex-1 overflow-hidden relative cursor-grab active:cursor-grabbing bg-[#0f1012]"
        onMouseDown={(e) => handleMouseDown(e)}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        onWheel={handleWheel}
      >
        <div
          className="absolute inset-0 pointer-events-none opacity-[0.15]"
          style={{
            backgroundImage: "radial-gradient(#555 1px, transparent 1px)",
            backgroundSize: `${20 * scale}px ${20 * scale}px`,
            backgroundPosition: `${offset.x}px ${offset.y}px`,
          }}
        />
        <div
          className="absolute origin-top-left transition-transform duration-75 ease-out will-change-transform"
          style={{
            transform: `translate(${offset.x}px, ${offset.y}px) scale(${scale})`,
            width: "100%",
            height: "100%",
          }}
        >
          <svg className="absolute top-0 left-0 w-[5000px] h-[5000px] pointer-events-none overflow-visible z-0">
            {connections}
            {connectingSource && (
              <line
                x1={connectingSource.startX}
                y1={connectingSource.startY}
                x2={mousePos.x}
                y2={mousePos.y}
                stroke="#3b82f6"
                strokeWidth="2"
                strokeDasharray="5,5"
                className="animate-pulse"
              />
            )}
          </svg>
          {filteredTables.map((table: any) => {
            const isMatch = table.isMatch;
            const isDimmed =
              (searchQuery && !isMatch) ||
              (hoveredTable && !relatedTableIds.has(table.id));
            const isHovered = hoveredTable === table.id;
            return (
              <div
                key={table.id}
                onMouseEnter={() => setHoveredTable(table.id)}
                onMouseLeave={() => setHoveredTable(null)}
                className={`
                  absolute w-[260px] bg-[#1a1b1e] border rounded-lg shadow-xl flex flex-col z-10 select-none group transition-all duration-200
                  ${
                    draggingTableId === table.id
                      ? "cursor-grabbing scale-105 z-50 ring-2 ring-blue-500/50"
                      : ""
                  }
                  ${
                    isHovered
                      ? "border-blue-500 shadow-blue-500/10 z-20"
                      : "border-[#3e3e42]"
                  }
                  ${
                    isDimmed ? "opacity-20 blur-[1px] grayscale" : "opacity-100"
                  } 
                  ${isMatch ? "ring-2 ring-yellow-500" : ""}
                `}
                style={{ left: table.position.x, top: table.position.y }}
              >
                <div
                  onMouseDown={(e) => handleMouseDown(e, table.id)}
                  className={`h-9 px-3 bg-[#252526] border-b border-[#3e3e42] rounded-t-lg flex items-center justify-between cursor-grab active:cursor-grabbing ${
                    isHovered ? "bg-blue-500/10" : ""
                  }`}
                >
                  <div className="flex items-center gap-2 font-bold text-slate-100 text-xs uppercase tracking-wider truncate">
                    <TableIcon
                      size={12}
                      className={isHovered ? "text-blue-400" : "text-slate-500"}
                    />{" "}
                    {table.name}
                  </div>
                  <div className="flex items-center gap-1">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDeleteTable(table.id);
                      }}
                      className="opacity-0 group-hover:opacity-100 p-1 hover:bg-red-500/20 hover:text-red-500 rounded transition-all"
                    >
                      <Trash2 size={12} />
                    </button>
                    <Focus
                      size={12}
                      className="opacity-0 group-hover:opacity-100 text-slate-500"
                    />
                  </div>
                </div>
                <div className="bg-[#1a1b1e] rounded-b-lg py-1">
                  {table.columns.map((col: Column, idx: number) => {
                    const isColMatch =
                      searchQuery &&
                      col.name
                        .toLowerCase()
                        .includes(searchQuery.toLowerCase());
                    return (
                      <div
                        key={idx}
                        className={`flex justify-between items-center text-[10px] px-3 py-1 hover:bg-[#2d2d2d] group/col relative ${
                          isColMatch ? "bg-yellow-500/20 text-yellow-200" : ""
                        }`}
                      >
                        <div className="flex items-center gap-2 overflow-hidden">
                          {col.isPk && (
                            <Key
                              size={8}
                              className="text-yellow-500 shrink-0"
                            />
                          )}
                          {col.isFk && (
                            <Share2
                              size={8}
                              className="text-blue-400 shrink-0"
                            />
                          )}
                          <span
                            className={`truncate ${
                              col.isPk
                                ? "font-bold text-white"
                                : "text-slate-300"
                            }`}
                          >
                            {col.name}
                          </span>
                        </div>
                        <span className="text-slate-500 font-mono text-[9px] ml-2">
                          {col.type}
                        </span>
                        <div
                          onMouseDown={(e) =>
                            handleColumnMouseDown(e, table.id, col.name)
                          }
                          className="absolute -right-2 w-4 h-4 flex items-center justify-center cursor-crosshair opacity-0 group-hover/col:opacity-100 transition-opacity"
                        >
                          <div
                            className={`w-2 h-2 rounded-full border border-[#1a1b1e] ${
                              col.isFk
                                ? "bg-blue-500"
                                : "bg-slate-500 hover:bg-white"
                            }`}
                          ></div>
                        </div>
                        {connectingSource &&
                          connectingSource.tableId !== table.id && (
                            <div
                              onMouseUp={(e) =>
                                handleColumnMouseUp(e, table.id)
                              }
                              className="absolute -left-2 w-4 h-4 flex items-center justify-center cursor-pointer z-50"
                            >
                              <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                            </div>
                          )}
                        {!connectingSource &&
                          isHovered &&
                          col.isFk &&
                          col.fkTargets &&
                          col.fkTargets.length > 0 && (
                            <div className="absolute -right-1 w-1.5 h-1.5 rounded-full border border-[#1a1b1e] bg-blue-500"></div>
                          )}
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {showMinimap && (
        <div className="absolute bottom-6 right-6 w-40 h-28 bg-[#1a1b1e] border border-[#3e3e42] rounded-lg shadow-2xl overflow-hidden hidden md:block opacity-80 hover:opacity-100 transition-opacity">
          <div className="w-full h-full relative bg-[#111]">
            {tables.map((t) => (
              <div
                key={t.id}
                className={`absolute rounded-[1px] ${
                  hoveredTable && !relatedTableIds.has(t.id)
                    ? "bg-slate-800"
                    : "bg-slate-500"
                }`}
                style={{
                  left: t.position.x * 0.04 + 10,
                  top: t.position.y * 0.04 + 10,
                  width: 260 * 0.04,
                  height: (40 + t.columns.length * 28) * 0.04,
                }}
              />
            ))}
            <div
              className="absolute border border-blue-500/50 bg-blue-500/10"
              style={{
                left: -offset.x * 0.04 + 10,
                top: -offset.y * 0.04 + 10,
                width: "100%",
                height: "100%",
              }}
            />
          </div>
          <button
            onClick={() => setShowMinimap(false)}
            className="absolute top-1 right-1 p-1 hover:bg-red-500/20 hover:text-red-500 rounded"
          >
            <X size={10} />
          </button>
        </div>
      )}
      {!showMinimap && (
        <button
          onClick={() => setShowMinimap(true)}
          className="absolute bottom-6 right-6 p-3 bg-[#1a1b1e] border border-[#3e3e42] rounded-lg shadow-xl text-slate-400 hover:text-white hidden md:block"
        >
          <Maximize size={16} />
        </button>
      )}

      {showImportModal && (
        <div className="absolute inset-0 bg-black/80 z-50 flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in zoom-in-95">
          <div className="w-full max-w-lg bg-[#252526] border border-[#3e3e42] rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[80vh]">
            <div className="p-4 border-b border-[#3e3e42] bg-[#2d2d2d] flex justify-between items-center">
              <h3 className="text-sm font-bold text-white uppercase tracking-widest flex items-center gap-2">
                <Share2 size={16} className="text-green-500" /> Import from
                Database
              </h3>
              <button onClick={() => setShowImportModal(false)}>
                <X size={18} className="text-slate-400 hover:text-white" />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-2 custom-scrollbar">
              {dbTables.length === 0 ? (
                <div className="text-center py-10 text-slate-500 text-sm">
                  No tables found.
                </div>
              ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {dbTables.map((t) => {
                    const isSelected = selectedDbTables.includes(t.id);
                    return (
                      <div
                        key={t.id}
                        onClick={() => toggleDbTableSelection(t.id)}
                        className={`flex items-center gap-3 p-3 rounded-lg cursor-pointer border transition-all ${
                          isSelected
                            ? "bg-blue-600/10 border-blue-600 text-white"
                            : "bg-[#1e1e1e] border-[#3e3e42] text-slate-400 hover:border-slate-500"
                        }`}
                      >
                        {isSelected ? (
                          <CheckSquare size={18} className="text-blue-500" />
                        ) : (
                          <Square size={18} />
                        )}
                        <div className="truncate font-medium text-xs">
                          {t.name}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
            <div className="p-4 border-t border-[#3e3e42] flex gap-2 bg-[#252526]">
              <button
                onClick={() => setShowImportModal(false)}
                className="flex-1 py-2 rounded-lg bg-[#3e3e42] hover:bg-[#4e4e52] text-xs font-bold text-white"
              >
                Cancel
              </button>
              <button
                onClick={executeImport}
                disabled={selectedDbTables.length === 0}
                className="flex-1 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-xs font-bold text-white shadow-lg"
              >
                Import
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
