import { TableData } from "../types/erd_type";

// --- HELPER: COLOR GENERATOR ---
export const generateStableColor = (str: string) => {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  const h = Math.abs(hash) % 360;
  return `hsl(${h}, 80%, 60%)`;
};

// --- HELPER: SQL GENERATOR ---
export const generateSQL = (tables: TableData[]) => {
  let sql = `-- Generated by LocalDB Architect\n\n`;
  tables.forEach((table) => {
    sql += `CREATE TABLE ${table.name} (\n`;
    const cols = table.columns.map((col) => {
      let type = col.type.toUpperCase();
      if (type === "STRING") type = "VARCHAR(255)";
      if (type === "NUMBER") type = "INT";
      if (type === "BOOLEAN") type = "BOOLEAN";
      let line = `  ${col.name} ${type}`;
      if (col.isPk) line += " PRIMARY KEY";
      return line;
    });
    sql += cols.join(",\n");
    sql += `\n);\n\n`;
  });
  tables.forEach((table) => {
    table.columns.forEach((col) => {
      if (col.isFk && col.fkTargets) {
        col.fkTargets.forEach((targetId) => {
          const targetTable = tables.find((t) => t.id === targetId);
          if (targetTable) {
            sql += `ALTER TABLE ${table.name} ADD CONSTRAINT fk_${table.name}_${col.name}\n`;
            sql += `  FOREIGN KEY (${col.name}) REFERENCES ${targetTable.name}(id);\n\n`;
          }
        });
      }
    });
  });
  return sql;
};
