import {
  Layout,
  Settings,
  Info,
  Clock,
  Power,
  FileText,
  FileSpreadsheet,
  CheckSquare,
  StickyNote,
  Calendar,
  PenTool,
  Table,
  Hourglass,
  TerminalSquare,
  Code2,
  GitBranch,
  Database,
  DatabaseZap,
  FileJson,
  Braces,
  RadioTower,
  Shield,
  Regex,
  Binary,
  Code,
  Library,
  Container,
  FolderTree,
  Palette,
  Type,
  Sticker,
  PaintBucket,
  BoxIcon,
  Film,
  Smartphone,
  Facebook,
  ImagePlay,
  TestTube,
  ClipboardList,
  Bug,
  Bot,
  Calculator,
  ArrowRightLeft,
  Languages,
  QrCode,
  ALargeSmall,
  ImageIcon,
  CloudSun,
  MapIcon,
  Newspaper,
  Globe,
  Gauge,
  MonitorSmartphone,
  Cast,
  Aperture,
  Camera,
  Mic,
  Wallet,
  ShieldCheck,
  WalletCards,
  FlaskConical,
  Target,
  Users,
  Droplets,
  ChefHat,
  Wind,
  Headphones,
  Music,
  Brush,
  Zap,
  BookOpen,
  BookOpenText,
  Book,
  Gamepad2,
  Swords,
  Castle,
  Flower,
  Sparkles,
  Dice6,
  Dices,
  Box,
  Layers,
  Activity,
} from "lucide-react";

export const MODULE_LIBRARY = [
  // --- SYSTEM ---
  { name: "Config", cat: "System", desc: "Manage Apps", icon: Layout },
  { name: "Settings", cat: "System", desc: "Preferences", icon: Settings },
  { name: "About", cat: "System", desc: "App Info", icon: Info },
  { name: "System", cat: "System", desc: "Monitor Info", icon: Activity },
  { name: "Time & Date", cat: "System", desc: "System Clock", icon: Clock },
  { name: "Power", cat: "System", desc: "Shutdown Timer", icon: Power },

  // --- OFFICE ---
  { name: "Word", cat: "Office", desc: "Editor & Docs", icon: FileText },
  { name: "Excel", cat: "Office", desc: "Spreadsheet", icon: FileSpreadsheet },
  { name: "PDF Tools", cat: "Office", desc: "Merge, Split", icon: FileText }, // Dùng tạm FileText hoặc import FileType2
  { name: "Task", cat: "Office", desc: "Daily to-dos", icon: CheckSquare },
  { name: "Note", cat: "Office", desc: "Quick memos", icon: StickyNote },
  {
    name: "Calendar",
    cat: "Office",
    desc: "Events & Schedule",
    icon: Calendar,
  },
  { name: "Markdown", cat: "Office", desc: "Markdown Editor", icon: FileText },
  { name: "Signature", cat: "Office", desc: "Create & Export", icon: PenTool },
  { name: "Table Studio", cat: "Office", desc: "Generator", icon: Table },
  { name: "Focus", cat: "Office", desc: "Pomodoro", icon: Clock },
  { name: "Hourglass", cat: "Office", desc: "Sand Timer", icon: Hourglass },

  // --- DEV ---
  {
    name: "Terminal",
    cat: "Dev",
    desc: "Virtual Machine",
    icon: TerminalSquare,
  },
  { name: "Code", cat: "Dev", desc: "Snippets & Notes", icon: Code2 },
  { name: "Git", cat: "Dev", desc: "Git Tools & Hub", icon: GitBranch },
  { name: "Database", cat: "Dev", desc: "Local SQL DB", icon: Database },
  {
    name: "ER Diagram",
    cat: "Dev",
    desc: "Schema Visualizer",
    icon: DatabaseZap,
  },
  { name: "JSON", cat: "Dev", desc: "Viewer & Editor", icon: FileJson },
  { name: "JSON Tools", cat: "Dev", desc: "Format & Diff", icon: Braces },
  { name: "Postman", cat: "Dev", desc: "API Client", icon: RadioTower },
  { name: "JWT Inspector", cat: "Dev", desc: "Debug Tokens", icon: Shield },
  { name: "Regex", cat: "Dev", desc: "Regex Tester", icon: Regex },
  { name: "Decoder", cat: "Dev", desc: "Morse / Base64", icon: Binary },
  { name: "Snippets", cat: "Dev", desc: "Code Library", icon: Code },
  { name: "Lib Hub", cat: "Dev", desc: "Package Manager", icon: Library },
  { name: "DevOps Tools", cat: "Dev", desc: "Cron & Docker", icon: Container },
  {
    name: "Tree Folder",
    cat: "Dev",
    desc: "Folder Structure",
    icon: FolderTree,
  },

  // --- DESIGN ---
  {
    name: "Dev Design",
    cat: "Design",
    desc: "Color & Contrast",
    icon: Palette,
  },
  { name: "Typography", cat: "Design", desc: "Scale & Fonts", icon: Type },
  { name: "Icon Picker", cat: "Design", desc: "Lucide Library", icon: Sticker },
  {
    name: "UI Factory",
    cat: "Design",
    desc: "Tạo code UI React",
    icon: PaintBucket,
  },
  { name: "3D Engine", cat: "Design", desc: "Unity-like View", icon: BoxIcon },
  { name: "Anim Studio", cat: "Design", desc: "CSS Motion Lib", icon: Film },
  {
    name: "Respon View",
    cat: "Design",
    desc: "Mobile Tester",
    icon: Smartphone,
  },
  {
    name: "Facebook Studio",
    cat: "Design",
    desc: "Mockup & Fonts",
    icon: Facebook,
  },
  {
    name: "Photo Booth",
    cat: "Design",
    desc: "Filters & Stickers",
    icon: ImagePlay,
  },

  // --- TEST ---
  { name: "Tester Studio", cat: "Test", desc: "Test Data Gen", icon: TestTube },
  {
    name: "TestCase",
    cat: "Test",
    desc: "Test Script Manager",
    icon: ClipboardList,
  },
  { name: "Bug Report", cat: "Test", desc: "Generator Tool", icon: Bug },

  // --- UTILITY ---
  { name: "AI Chat", cat: "Utility", desc: "Assistant", icon: Bot },
  { name: "Calc", cat: "Utility", desc: "Math tool", icon: Calculator },
  { name: "Convert", cat: "Utility", desc: "Unit Tools", icon: ArrowRightLeft },
  { name: "Trans", cat: "Utility", desc: "Multi-language", icon: Languages },
  { name: "QR Gen", cat: "Utility", desc: "Make Codes", icon: QrCode },
  {
    name: "Gen Data",
    cat: "Utility",
    desc: "Lorem & Fake Data",
    icon: ALargeSmall,
  },
  {
    name: "Image Tools",
    cat: "Utility",
    desc: "Compress & Convert",
    icon: ImageIcon,
  },
  { name: "Weather", cat: "Utility", desc: "Forecast", icon: CloudSun },
  { name: "Maps", cat: "Utility", desc: "World view", icon: MapIcon },
  { name: "News", cat: "Utility", desc: "VNExpress RSS", icon: Newspaper },
  { name: "Socials", cat: "Utility", desc: "Quick Links", icon: Globe },
  { name: "Speed", cat: "Utility", desc: "Network Test", icon: Gauge },
  {
    name: "Device Hub",
    cat: "Utility",
    desc: "Sync & Transfer",
    icon: MonitorSmartphone,
  },
  { name: "Cast Hub", cat: "Utility", desc: "Screen Mirror", icon: Cast },
  { name: "Share", cat: "Utility", desc: "File Sharing", icon: Cast },
  { name: "Capture", cat: "Utility", desc: "Screenshot Tool", icon: Aperture },
  { name: "Camera", cat: "Utility", desc: "Photo Booth", icon: Camera },
  { name: "Record", cat: "Utility", desc: "Voice Memos", icon: Mic },

  // --- FINANCE ---
  { name: "Budget", cat: "Finance", desc: "Expense Tracker", icon: Wallet },
  {
    name: "Vault",
    cat: "Finance",
    desc: "Passwords & Bank",
    icon: ShieldCheck,
  },
  { name: "Crypto", cat: "Finance", desc: "Encrypt Data", icon: ShieldCheck },
  {
    name: "Portfolio",
    cat: "Finance",
    desc: "Crypto & Stocks",
    icon: WalletCards,
  },
  {
    name: "Simulator",
    cat: "Finance",
    desc: "Loan & Buy vs Rent",
    icon: FlaskConical,
  },
  { name: "Goal Tracker", cat: "Finance", desc: "Set & Achieve", icon: Target },
  {
    name: "Genealogy",
    cat: "Finance",
    desc: "Family Tree Builder",
    icon: Users,
  },
  {
    name: "Body & Hydro",
    cat: "Finance",
    desc: "Tracker & BMI",
    icon: Droplets,
  },
  {
    name: "Kitchen Finder",
    cat: "Finance",
    desc: "Cook & Drink",
    icon: ChefHat,
  },
  { name: "Zen", cat: "Finance", desc: "Focus & Relax", icon: Wind },

  // --- MEDIA ---
  { name: "Music", cat: "Media", desc: "Lofi Player", icon: Headphones },
  { name: "Piano", cat: "Media", desc: "Synthesia Style", icon: Music },
  { name: "Board", cat: "Media", desc: "Sketch & Notes", icon: Brush },
  { name: "Speed Read", cat: "Media", desc: "RSVP Reading", icon: Zap },
  { name: "Manga", cat: "Media", desc: "Reading Manga", icon: BookOpen },
  {
    name: "Writer Studio",
    cat: "Media",
    desc: "Novel Studio",
    icon: BookOpenText,
  },
  { name: "Wiki", cat: "Media", desc: "Knowledge Base", icon: Book },

  // --- GAME ---
  { name: "Game", cat: "Game", desc: "Tetris Neon", icon: Gamepad2 },
  { name: "RPG", cat: "Game", desc: "Eternity Quest", icon: Swords },
  { name: "Defense", cat: "Game", desc: "Tower Defense", icon: Castle },
  { name: "PVZ", cat: "Game", desc: "Plants vs Zombies", icon: Flower },
  { name: "Mystic Space", cat: "Game", desc: "Tarot & Zodiac", icon: Sparkles },
  { name: "Dice Master", cat: "Game", desc: "Roll & Luck", icon: Dice6 },
  { name: "Decision Wheel", cat: "Game", desc: "Spin to Decide", icon: Dices },
];

export const TECH_STACK = [
  {
    name: "Tauri v2",
    icon: ShieldCheck,
    color: "text-orange-500 dark:text-orange-400",
    bg: "bg-orange-500/10",
  },
  {
    name: "React 18",
    icon: Code2,
    color: "text-cyan-600 dark:text-cyan-400",
    bg: "bg-cyan-500/10",
  },
  {
    name: "TypeScript",
    icon: Box,
    color: "text-blue-600 dark:text-blue-500",
    bg: "bg-blue-500/10",
  },
  {
    name: "Vite",
    icon: Zap,
    color: "text-yellow-500 dark:text-yellow-400",
    bg: "bg-yellow-500/10",
  },
  {
    name: "Zustand",
    icon: Layers,
    color: "text-purple-600 dark:text-purple-400",
    bg: "bg-purple-500/10",
  },
  {
    name: "Tailwind",
    icon: Sparkles,
    color: "text-teal-600 dark:text-teal-400",
    bg: "bg-teal-500/10",
  },
];

export const APP_INFO = {
  name: "OverDesk",
  version: "2.0.0",
  build: "2026.01.18.RC2",
  author: "Trung Hoàng (Melody)",
  role: "Fullstack Engineer",
  slogan: "Your Ultimate Productivity Companion",
  socials: {
    github: "https://github.com",
    web: "https://overdesk.app",
    twitter: "https://twitter.com",
  },
};
